import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Science Research Center",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
        <Navbar /> 
        {children}
        <Footer />
    </>
     
  );
}
